AtividadeLemafJoseRenato/AtividadeLemafJoseRenato/Controllers/ReuniaoController.cs
using AtividadeLemafJoseRenato.Executores.Reuniao;
using AtividadeLemafJoseRenato.Fronteiras.Executor.Geral;
using AtividadeLemafJoseRenato.Fronteiras.Executor.Reuniao;
using AtividadeLemafJoseRenato.Util;
using AtividadeLemafJoseRenato.Util.Log;
using Fronteira.Dtos;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AtividadeLemafJoseRenato.Controllers
{
    public class ReuniaoController : Controller
    {
        // GET: Reuniao
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult AgendarReuniao(DateTime dataInicio, DateTime dataFim, int quantidadePessoas,
            bool precisaInternet, bool precisaWebcam)
        {
            try
            {
                var selecionarExecutor = new SelecionarOuSugerirSalaExecutor();

                AgendamentoDto agendamentoDto = new AgendamentoDto()
                {
                    DataInicio = dataInicio,
                    DataFim = dataFim,
                    QuantidadePessoas = quantidadePessoas,
                    NecessitaAcessoInternet = precisaInternet,
                    NecessitaTvEWebcam = precisaWebcam
                };
                SelecionarOuSugerirSalaRequisicao requisicaoSolicitarSala = new SelecionarOuSugerirSalaRequisicao(new LogContexto(TipoFluxoLog.SelecionarSala, null))
                {
                    InformacoesAgendamentoSala = agendamentoDto
                };
                SelecionarOuSugerirSalaResultado resultadoSolicitarSala = selecionarExecutor.Executar(requisicaoSolicitarSala);
                if (resultadoSolicitarSala.IdSalaAgendada.HasValue)
                    return Json(new { sucesso = true, sala = resultadoSolicitarSala.IdSalaAgendada.Value }, JsonRequestBehavior.AllowGet);
                else
                {
                    string mensagem = "Não foi possível agendar uma sala. Sugestões:"; 
                    string sugestoes = string.Empty;
                    foreach(var sugestaoDto in resultadoSolicitarSala.ListaSugestoesAgendamentos)
                    {
                        sugestoes = sugestoes + $" Sala {sugestaoDto.IdSalaSugerida}, DataInicio: {sugestaoDto.DataInicioSugerida.ToString("dd-MM-yyyy HH:mm")}, DataFim {sugestaoDto.DataFimSugerida.ToString("dd-MM-yyyy HH:mm")} ";
                    }
                    return Json(new { sucesso = false, mensagem = mensagem }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (InformacaoException ex)
            {
                return Json(new { sucesso = false, mensagem = ex.Message }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                EnviarEmailRequisicao requisicaoEnviarEmail = new EnviarEmailRequisicao(new LogContexto("EnviarEmail", null))
                {

                    Assunto = "Erro na aplicação Agendamento de Reunião",
                    CorpoEmail = ex.Message + ex.InnerException + ex.StackTrace,
                    Remetente = ConfigurationManager.AppSettings["EMAIL_REMETENTE"],
                    Destinatario = ConfigurationManager.AppSettings["EMAIL_TESTE"],
                };
                new EnviarEmailExecutor().Executar(requisicaoEnviarEmail);
            }
            return Json(new { sucesso = false, mensagem = "Ocorreu um erro!" }, JsonRequestBehavior.AllowGet);
        }
    }
}

AtividadeLemafJoseRenato/AtividadeLemafJoseRenato/Views/Reuniao/Index.cshtml
<div class="container-fluid">
    <div class="row-fluid">
        <h3 class="page-header">Agendamento de Reuniões</h3>
        <div class="well well-sm" style="padding-left:40px;">
            <div class="form-group row">
                <label for="data-inicio" class="col-2 col-form-label">Início da Reunião</label>
                <div class="col-10">
                    <input class="form-control" type="datetime-local" value="" id="data-inicio">
                </div>
            </div>
            <div class="form-group row">
                <label for="data-fim" class="col-2 col-form-label">Término da reunião</label>
                <div class="col-10">
                    <input class="form-control" type="datetime-local" value="" id="data-fim">
                </div>
            </div>
            <div class="form-group row">
                <label for="quantidade-pessoas" class="col-2 col-form-label">Quantidade de Pessoas</label>
                <div class="col-10">
                    <input class="form-control" type="text" value="" id="quantidade-pessoas">
                </div>
            </div>
            <div class="form-group row">
                <label for="ddl-internet" class="col-2 col-form-label">Precisa de Internet</label>
                <div class="col-10">
                    <select class="form-control" id="ddl-internet">
                        <option value="false">Não</option>
                        <option value="true">Sim</option>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="ddl-webcam" class="col-2 col-form-label">Precisa de Internet</label>
                <div class="col-10">
                    <select class="form-control" id="ddl-webcam">
                        <option value="false">Não</option>
                        <option value="true">Sim</option>
                    </select>
                </div>
            </div>
            <div class="span3" style="text-align:right">
                <br />
                <button id="btn-agendar" type="button" class="btn btn-primary btn-lg">&nbsp;Agendar</button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="~/Scripts/agendar-reuniao.js"></script>
<script type="text/javascript">
    var urlAgendarReuniao = '@Url.Action("AgendarReuniao", "Reuniao")';
    $('#quantidade-pessoas').val('5')
</script>

AtividadeLemafJoseRenato/AtividadeLemafJoseRenato/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>
</body>
</html>